version: "3.9"

services:
  bank-analyst:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-ai-analyst
    ports:
      - "5000:5000"    
      - "11434:11434"  
    volumes:
      - ./reports:/app/reports
      - ./data:/app/data
      - ./logs:/app/logs
      - bank_data:/app/bank_data
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    networks:
      - bank-network

  nginx:
    image: nginx:alpine
    container_name: bank-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - bank-analyst
    networks:
      - bank-network
    profiles:
      - production

networks:
  bank-network:
    driver: bridge

volumes:
  bank_data:
    driver: local
